use_frameworks!

platform :ios, '8.0'

target 'XFReadWriteLocker_Example' do
  pod 'XFReadWriteLocker', :path => '../'

  target 'XFReadWriteLocker_Tests' do
    inherit! :search_paths

    
  end
end
